quarkus.log.level=INFO
quarkus.banner.enabled=false
quarkus.native.additional-build-args=--enable-native-access=ALL-UNNAMED,\
--initialize-at-run-time=org.jline.terminal.impl.ffm\\,org.jline.nativ

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:./leyden-analyzer.db
quarkus.datasource.username=sa
quarkus.datasource.password=

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=false