# I'm lazy and trust the tests we have. What can go wrong? :D
# This job auto-merges dependabot dependencies.
# If they pass all mandatory tests (which includes smoke tests), just merge the PR.
name: Dependabot Auto Manage
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'app/dependabot'
    steps:
      - uses: ad/dependabot-auto-approve@3cad5f42e79296505473325ac6636be897c8b8a1
        with:
          github-token: ${{ secrets.PAT_TOKEN }}  # Use your PAT secret name
          dependency-type: 'all'
          auto-merge: 'true'
          add-label: 'auto-merged'
