# I'm lazy and trust the tests we have. What can go wrong? :D
# This job auto-merges dependabot dependencies.
# If they pass all mandatory tests (which includes smoke tests), just merge the PR.
name: Dependabot Auto Manage
on:
  pull_request:
  status:
  check_run:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'app/dependabot'
    steps:
      - uses: actions/checkout@v7
      - name: Auto-Merge PR
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run:  gh pr merge --repo "Delawen/leyden-analyzer" --auto --delete-branch "${{ github.event.pull_request.number }}"
      - name: Add label to PR
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh pr edit --repo "Delawen/leyden-analyzer" --add-label "auto-merged" "${{ github.event.pull_request.number }}"
