name: "PR mandatory checks"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  publish:
    name: "PR Mandatory Checks"
    if:  github.event.pull_request.user.id != 49699333
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: peternied/check-pull-request-description-checklist@ec79db61b595a5f3bea6df7963f818c013845b89
        with:
          checklist-items: |
                  This is not AI generated and I own the assets pushed
                  I have added tests that prove my fix is effective or that my feature works
  whoami:
    name: "PR Mandatory Checks"
    if:  github.event.pull_request.user.id == 49699333
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Who am I
        shell: bash
        run: echo "Skip!"

