# This workflow will build and create a release when a tag following semver
name: Release

on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+', '[0-9]+.[0-9]+.[0-9]+-*']

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
        cache: maven

    - name: Build
      run:  ./mvnw verify -Dquarkus.package.jar.type=uber-jar

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/*-runner.jar
        make_latest: true
        prerelease: false
        generate_release_notes: true
        draft: true
